name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore LiveX
    - name: Build for Windows
      run: dotnet publish -r win-x64 -c Release /p:PublishSingleFile=true /p:PublishTrimmed=true -o artifacts/livex-win-x64 LiveX
    - name: Build for macOS
      run: dotnet publish -r osx-x64 -c Release /p:PublishSingleFile=true /p:PublishTrimmed=true -o artifacts/livex-osx-x64 LiveX
    - name: Build for Linux
      run: dotnet publish -r linux-x64 -c Release /p:PublishSingleFile=true /p:PublishTrimmed=true -o artifacts/livex-linux-x64 LiveX
    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v2
      with:
        name: livex-win-x64
        path: artifacts/livex-win-x64
    - name: Upload macOS artifacts
      uses: actions/upload-artifact@v2
      with:
        name: livex-osx-x64
        path: artifacts/livex-osx-x64
    - name: Upload Linux artifacts
      uses: actions/upload-artifact@v2
      with:
        name: livex-linux-x64
        path: artifacts/livex-linux-x64
